name: Semgrep
on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{secrets.SEMGREP_APP_TOKEN}}
      - name: Create version
        id: create_version
        run: echo "VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
        env:
          VERSION: ${{ steps.create_version.outputs.VERSION }}
      - name: Create artifact directories
        run: mkdir -p artifacts/${{github.repository}}
      - name: Build artifact
        run: |
          echo "${{ github.repository }}" > artifacts/${{ github.repository }}.txt
          echo "Version: $VERSION" >> artifacts/${{ github.repository }}.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: artifacts/
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.DEVELOPER_TOKEN}}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: New version ${{ env.VERSION }} created.
          draft: false
          prerelease: false
      - name: Commit and push
        run: |
          git config --global user.name 'cloudandcoffe'
          git config --global user.email 'cloudandcoffe@gmail.com'
          git add .
          git commit -m "New version created: ${{env.VERSION}}"
          git push
      - name: List tags
