name: Semgrep
on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - master
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      - name: Create version
        run: echo "VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: Build artifact
        run: |
          mkdir -p artifacts/${{ github.repository }}
          echo "${{ github.repository }}" > artifacts/${{ github.repository }}.txt
          echo "Version: $VERSION" >> artifacts/${{ github.repository }}.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: artifacts/
          echo "Version: $VERSION" >> artifacts/${{ github.repository }}.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: artifacts/
